---

- hosts: host
  remote_user: root

  vars:
    nginx_apt_key: "http://nginx.org/keys/nginx_signing.key"
    ajenti_apt_key: "http://repo.ajenti.org/debian/key"
    nginx_proxmox_conf: "proxmox"

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart ajenti
      service: name=ajenti state=restarted

  pre_tasks:
    - name: Remove PVE Enterprise repo
      file: >
        path=/etc/apt/sources.list.d/pve-enterprise.list
        state=absent

    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

    - name: Remove Proxmox subscription message
      replace: >
        dest=/usr/share/pve-manager/ext4/pvemanagerlib.js
        regexp="data.status !== 'Active'"
        replace="false"

  tasks:
    - name: Add Nginx apt key
      apt_key: url={{ nginx_apt_key }} state=present

    - name: Add Nginx apt repo
      apt_repository: >
        repo="{{ item }}"
        state=present
        update_cache=yes
      with_items:
        - "deb http://nginx.org/packages/debian/ wheezy nginx"
        - "deb-src http://nginx.org/packages/debian/ wheezy nginx"

    - name: Install Nginx
      apt: name={{ item }} state=present
      with_items:
        - nginx
      notify:
        - restart nginx

    - name: Create Nginx conf directories
      file: path="/etc/nginx/{{ item }}" state=directory
      with_items:
        - ssl
        - sites-available
        - sites-enabled

    - name: Auto include Nginx files from sites-enabled
      lineinfile: >
        dest=/etc/nginx/nginx.conf
        regexp="^( *)include /etc/nginx/conf\.d/\*\.conf;"
        line="\1include /etc/nginx/sites-enabled/*;"
        backrefs=yes
      notify:
        - restart nginx

    - name: Generate self signed SSL certificate
      command:
        openssl req -new -nodes -x509 -subj "/C=FR/ST=France/L=Lyon/O=lobr/CN={{ inventory_hostname }}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca
        creates=/etc/nginx/ssl/server.crt
      notify:
        - restart nginx

    - name: Add Nginx host config from template
      template: >
        src=template_nginx_host.j2
        dest="/etc/nginx/sites-available/{{ nginx_proxmox_conf }}"

    - name: Link Nginx config to sites-enable
      file: >
        src="/etc/nginx/sites-available/{{ item }}"
        dest="/etc/nginx/sites-enabled/{{ item }}"
        state=link
      with_items:
        - "{{ nginx_proxmox_conf }}"
      notify:
        - restart nginx

    - name: Add Ajenti apt key
      apt_key: url={{ ajenti_apt_key }} state=present

    - name: Add Ajenti apt repo
      apt_repository: >
        repo="deb http://repo.ajenti.org/debian main main debian"
        state=present
        update_cache=yes

    - name: Install Ajenti
      apt: name={{ item }} state=present
      with_items:
        - ajenti
      notify:
        - restart ajenti

    - name: Import Debian 8 templates
      get_url:
       url="http://download.openvz.org/template/precreated/{{ item }}"
       dest="/var/lib/vz/template/cache/{{ item }}"
      with_items:
        - "debian-8.0-x86_64.tar.gz"
        - "debian-8.0-x86_64-minimal.tar.gz"