---

- name: Plex
  hosts: media
  remote_user: root

  vars_files:
    - ../vars.yml

  handlers:
    - name: restart plex
      service: name=plexmediaserver state=restarted

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Add Plex apt key
      apt_key: url={{ plex_apt_key }} state=present

    - name: Add Plex apt repo
      apt_repository: >
        repo="{{ item }}"
        state=present
        update_cache=yes
      with_items: "{{ plex_repo }}"

    - name: Install Plex
      apt: name={{ item }} state=present
      with_items:
        - plexmediaserver
      notify:
        - restart plex

- name: Deluge
  hosts: media
  remote_user: root

  vars_files:
    - ../vars.yml

  handlers:
    - name: restart deluge
      service: name=deluge-web state=restarted

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Install Deluge
      apt: name={{ item }} state=present
      with_items:
        - deluged
        - deluge-webui

    - name: Create web daemon scripts
      template: >
        src="../templates/{{ item.src }}"
        dest="{{ item.dest }}"
      with_items:
        - { src: "deluged_service.j2", dest: "/etc/systemd/system/deluged.service" }
        - { src: "deluge_web_service.j2", dest: "/etc/systemd/system/deluge-web.service" }
      notify:
        - restart deluge

- name: Owncloud
  hosts: media
  remote_user: root

  vars_files:
    - ../vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

    - name: Install ansible MySQL dependencies
      apt: name=python-mysqldb state=present

  tasks:
    - name: Add Owncloud apt key
      apt_key: url={{ owncloud_apt_key }} state=present

    - name: Add Owncloud apt repo
      apt_repository: >
        repo="{{ item }}"
        state=present
        update_cache=yes
      with_items: "{{ owncloud_repo }}"

    - name: Install Owncloud
      apt: name={{ item }} state=present
      with_items:
        - owncloud

    - name: Install MySQL
      apt: name={{ item }} state=present
      with_items:
        - mysql-server

    - name: Create database
      mysql_db: name={{ owncloud_db_name }} state=present

    - name: Create owncloud database user
      mysql_user: >
        name="{{ owncloud_db_user }}"
        password="{{ owncloud_db_password }}"
        priv="{{ owncloud_db_name }}.*:ALL"
        state=present

- name: Create users groups and shared media folder
  hosts: media
  remote_user: root

  vars_files:
    - ../vars.yml

  tasks:
    - name: Create shared group
      group: name="{{ apache_group }}" state=present

    - name: Make sure users are created
      user:
        name="{{ item }}"
        group="{{ apache_group }}"
      with_items:
        - "{{ apache_user }}"
        - "{{ deluge_user }}"
        - "{{ plex_user }}"

    - name: Create shared media folder
      file: >
        path="{{ media_folder }}"
        owner="{{ apache_user }}"
        group="{{ apache_group }}"
        state=directory
        recurse=yes
        mode=0770

    - debug: msg=|
        The install is over. Here are the manual steps missing:
        * Configure Plex by launching "ssh ip.address.of.server -L 8888:localhost:32400", and allowing remote access for manual port 32400
        * Change Plex default group to "www-data" in "/lib/systemd/system/plexmediaserver.service" and restart "plexmediaserver"
        * Configure Owncloud. Add "umask(007);" to "/var/www/owncloud/config/config.php" and do a "chmod 770 -R {{ media_folder }}".
        * Configure Deluge to download in correct directory