---

- name: Plex
  hosts: media
  remote_user: root

  vars_files:
    - ../vars.yml

  handlers:
    - name: restart plex
      service: name=plexmediaserver state=restarted

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Add Plex apt key
      apt_key: url={{ plex_apt_key }} state=present

    - name: Add Plex apt repo
      apt_repository: >
        repo="{{ item }}"
        state=present
        update_cache=yes
      with_items: "{{ plex_repo }}"

    - name: Install Plex
      apt: name={{ item }} state=present
      with_items:
        - plexmediaserver
      notify:
        - restart plex

- name: Deluge
  hosts: media
  remote_user: root

  handlers:
    - name: restart deluge
      service: name=deluge-web state=restarted

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Install Deluge
      apt: name={{ item }} state=present
      with_items:
        - deluged
        - deluge-webui

    - name: Create web daemon scripts
      template: >
        src="../templates/{{ item.src }}"
        dest="{{ item.dest }}"
      with_items:
        - { src: "deluged_service.j2", dest: "/etc/systemd/system/deluged.service" }
        - { src: "deluge_web_service.j2", dest: "/etc/systemd/system/deluge-web.service" }
      notify:
        - restart deluge

- name: Shared folder
  hosts: media
  remote_user: root

  vars_files:
    - ../vars.yml

  tasks:
    - name: Create media folders
      file: >
        path="{{ media_folder }}/{{ item }}"
        owner="{{ plex_user }}"
        group="{{ plex_group }}"
        state=directory
        recurse=yes
        mode=0755
      with_items:
        - "Downloads"
        - "Movies"
        - "Series"



   