---

- hosts: "{{ host }}"
  remote_user: "{{ remote_usr }}"

  vars_files:
    - ../vars.yml

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Add Nginx apt key
      apt_key: url={{ nginx_apt_key }} state=present

    - name: Add Nginx apt repo
      apt_repository: >
        repo="{{ item }}"
        state=present
        update_cache=yes
      with_items: "{{ nginx_repos }}"

    - name: Install Nginx
      apt: name={{ item }} state=present
      with_items:
        - nginx
      notify:
        - restart nginx

    - name: Create Nginx conf directories
      file: path="/etc/nginx/{{ item }}" state=directory
      with_items:
        - ssl
        - sites-available
        - sites-enabled

    - name: Auto include Nginx files from sites-enabled
      lineinfile: >
        dest=/etc/nginx/nginx.conf
        regexp="^( *)include /etc/nginx/conf\.d/\*\.conf;"
        line="\1include /etc/nginx/sites-enabled/*;"
        backrefs=yes
      notify:
        - restart nginx

    - name: Generate self signed SSL certificate
      command:
        openssl req -new -nodes -x509 -subj "/C=FR/ST=France/L=Lyon/O=lobr/CN={{ inventory_hostname }}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca
        creates=/etc/nginx/ssl/server.crt
      notify:
        - restart nginx

    - name: Add Nginx host config from template
      template: >
        src=../templates/nginx_{{ item }}.j2
        dest="/etc/nginx/sites-available/{{ item }}"
      with_items: "{{ nginx_confs }}"

    - name: Link Nginx config to sites-enable
      file: >
        src="/etc/nginx/sites-available/{{ item }}"
        dest="/etc/nginx/sites-enabled/{{ item }}"
        state=link
      with_items: "{{ nginx_confs }}"
      notify:
        - restart nginx

